config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :items, only: [:index]
  end

  resources :items

  resources :orders, except: %i[new create]

  resources :cart, only: [:show] do
    member do
      get 'add'
      get 'remove'
      put 'quantity'
    end
    resource :orders, only: [:new]
  end

  namespace :api do
    namespace :v1 do
      resources :items
      resources :categories
    end
  end

  root to: 'welcome#index'
end

app/models/welcome.rb
# frozen_string_literal: true

class Welcome < ApplicationRecord
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @categories = Category.includes(:items)
    if user_signed_in?
      @cart = current_user.cart || current_user.create_cart
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/index.html.erb
<div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
</div>

<div class="">
  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right ml-auto p" id="sidebar-wrapper">
      <div class="list-group list-group-flush">
          <%= link_to 'Items', items_path, class: "list-group-item list-group-item-action bg-light" %>
          <%= link_to 'Categories', categories_path, class: "list-group-item list-group-item-action bg-light" %>
        <%= link_to 'Orders', orders_path, class: "list-group-item list-group-item-action bg-light" %>
      </div>
    </div>
    <div id="page-content-wrapper" class="resize">
      <div class="row">
        <% @categories.each do |category| %>
          <div class="col-sm-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title card-header"><%= category.title%></h5>
                  <% category.items.each do |item| %>
                    <p class="border border-info pl-3">
                      <%= link_to item.title, item_path(item) %>
                    </p>
                  <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>