config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :items, only: [:index]
  end

  resources :items

  resources :orders, except: %i[new create]

  resources :cart, only: [:show] do
    member do
      get 'add'
      get 'remove'
      put 'quantity'
    end
    resource :orders, only: [:new]
  end

  namespace :api do
    namespace :v1 do
      resources :items
      resources :categories
    end
  end

  root to: 'welcome#index'
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include Avatar

  has_many :line_items
  has_many :orders, through: :line_items, dependent: :destroy

  has_many :item_categories
  has_many :categories, through: :item_categories

  has_many :cart_items
  has_many :carts, through: :cart_items, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  after_commit :add_default_image, on: %i[create update]

  private

  def add_default_image
    get_avatar('item_avatar.jpeg')
  end
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api::V1
  class ItemsController < ApplicationController
    def index
      @items = Item.all
      render json: @items
    end

    def show
      @item = Item.find(params[:id])
      render json: @item
    end

    def new
      @item = Item.new
      authorize @item
    end

    def edit
      @item = Item.find(params[:id])
      authorize @item
    end

    def create
      @item = Item.new(item_params)
      authorize @item

      if @item.save
        render json: @item
      else
        render 'new'
      end
    end

    def update
      @item = Item.find(params[:id])
      authorize @item

      if @item.update(item_params)
        render json: @item
      else
        render 'edit'
      end
    end

    def destroy
      @item = Item.find(params[:id])
      authorize @item

      if @item.destroy
        flash[:notice] = 'You have successfully Deleted.'
        redirect_to items_path
      end
    end

    private

    def item_params
      params.require(:item).permit(:title, :description, :price, :availability, :image, category_ids: [])
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    if params[:category_id].nil?
      @items = Item.all.page(params[:page]).per(3)
    else
      category = Category.find(params[:category_id])
      @items = category.items.page(params[:page]).per(3)
    end
    authorize @items
  end

  def show
    @item = Item.find(params[:id])
    authorize @item
  end

  def new
    @item = Item.new
    authorize @item
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    authorize @item

    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])
    authorize @item

    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item

    if @item.destroy
      flash[:notice] = 'You have successfully Deleted.'
      redirect_to items_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :availability, :image, category_ids: [])
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def add_or_remove(item)
    flag = false
    if user_signed_in?
      current_user.cart.cart_items.each do |cart_item|
        flag = true if cart_item.item.id == item.id
      end
      if flag
        link_to 'Remove', remove_cart_path(item), remote: true if item.availability
      else
        link_to 'Add', add_cart_path(item), remote: true if item.availability
      end
    else
      link_to 'Add', add_cart_path(item), remote: true if item.availability
    end
  end
end

app/views/items/_form.html.erb
<%= form_with model: @item, local: true do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, min: 1, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :Categories %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :title %> <br>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <% availability = [true, false] %>
    <%= form.label :availability %>
    <%= form.select :availability, options_for_select(availability) %>
  </div>

  <p>
    <br>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render partial: 'shared/error', locals: { resource: @item } %>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'shared/delete' %>

<h1 class='text-center'>Listing Items</h1>

<div class='container'>
  <table class=table>
    <thead>
      <tr>
        <th>Avatar</th>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>View Item</th>
        <% if user_signed_in? && current_user.admin? %>
        <th colspan=3></th>
        <% else %>
        <th style="width: 120px">Add to Cart</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= image_tag(item.image, class: 'rounded-circle', size: "50x50") %></td>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= item.price %></td>
          <td><%= link_to 'Show', item_path(item) %></td>
          <% if current_user&.admin? %>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <td class="text-center" id='<%= item.id %>' > <%= add_or_remove(item) %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @items %>

  <br>
<% if current_user&.admin? %>
  <%= link_to 'New Item', new_item_path %>
<% end %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render partial: 'shared/error', locals: { resource: @item } %>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<% if current_user&.admin? %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back', items_path %>