config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :items, only: [:index]
  end

  resources :items

  resources :orders, except: %i[new create]

  resources :cart, only: [:show] do
    member do
      get 'add'
      get 'remove'
      put 'quantity'
    end
    resource :orders, only: [:new]
  end

  namespace :api do
    namespace :v1 do
      resources :items
      resources :categories
    end
  end

  root to: 'welcome#index'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :item_categories
  has_many :items, through: :item_categories, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/controllers/api/v1/categories_controller.rb
# frozen_string_literal: true

module Api::V1
  class CategoriesController < ApplicationController
    def index
      @categories = Category.all
      render json: @categories
    end

    def show
      @category = Category.find(params[:id])
      render json: @category
    end

    def new
      @category = Category.new
    end

    def edit
      @category = Category.find(params[:id])
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        render json: @category, status: :created
      else
        render json: @category.errors, status: :unprocessable_entity
      end
    end

    def update
      @category = Category.find(params[:id])

      if @category.update(category_params)
        render json: @category
      else
        render json: @category.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @category = Category.find(params[:id])

      if @category.destroy
        head :no_content, status: :ok
      else
        render json: @category.errors, status: :unprocessable_entity
      end
    end

    private

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all.page(params[:page]).per(3)
    authorize @categories
  end

  def show
    @category = Category.find(params[:id])
    authorize @category
  end

  def new
    @category = Category.new
    authorize @category
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    authorize @category

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    authorize @category
    @category.destroy

    flash[:notice] = if @category.destroy
                       'You have successfully Deleted.'
                     else
                       'Category Not Deleted.'
                     end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  def quantity_value(cart, item)
    quantity = CartItem.find_by(cart: cart, item: item).quantity
    quantity.nil? ? 1 : quantity
  end
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |form| %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, autofocus: true %>
  </div>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Categories</h1>

<%= render partial: 'shared/error', locals: { resource: @category } %>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render 'shared/delete' %>

<h1 class='text-center'>Listing Categories</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
          <% if current_user&.admin? %>
            <td><%= link_to 'Show', category_path(category) %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <td><%= link_to 'Show Items', category_items_path(category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @categories %>

<br>

<% if current_user&.admin? %>
  <%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: 'shared/error', locals: { resource: @category } %>

<%= render partial: 'shared/error', locals: { resource: @category } %>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

<%= link_to 'Dashbaord', '/' %>

app/views/categories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>